name: 'delivery_platform'
version: '1.0.0'
config-version: 2

profile: 'delivery_platform'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  delivery_platform:
    # Staging models materialize as views by default
    staging:
      +materialized: view
    # Mart models (dimensions & facts) materialize as tables for performance
    marts:
      +materialized: table
