locals {
  # Common name prefix applied to every resource.
  name_prefix = "${var.project_name}-${var.environment}"

  # Resolved bucket names — use explicit override if provided, otherwise derive from prefix.
  data_lake_bucket_name      = var.data_lake_bucket_name != "" ? var.data_lake_bucket_name : "${local.name_prefix}-data-lake"
  athena_results_bucket_name = var.athena_results_bucket_name != "" ? var.athena_results_bucket_name : "${local.name_prefix}-athena-results"

  # S3 data lake zone prefixes — must stay in sync with config/settings.py.
  s3_zones = ["raw", "validated", "processed", "analytics"]

  # Glue / Athena identifiers.
  glue_database_raw = "${local.name_prefix}_raw"
  athena_workgroup  = local.name_prefix

  # Lambda deployment archive is generated by Terraform from the ingestion package.
  lambda_handler_source = "${path.root}/../ingestion/lambda_handler.py"
  lambda_archive_output = "${path.root}/.terraform/lambda_ingestion_handler.zip"
}
